// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {inference} from '../models';
import {mcp} from '../models';

export function DeleteAstGrep():Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DeleteScipIndexer(arg1:string):Promise<void>;

export function DiscoverMarkdownFiles(arg1:string):Promise<Array<main.MarkdownEntry>>;

export function DownloadModel(arg1:string,arg2:string):Promise<void>;

export function FocusWorkspaceClient(arg1:number):Promise<void>;

export function GetAstGrepStatus():Promise<Record<string, any>>;

export function GetCommunityRuleDetails(arg1:string):Promise<Record<string, any>>;

export function GetDownloadProgress(arg1:string):Promise<number>;

export function GetFileContent(arg1:string,arg2:string):Promise<string>;

export function GetGraphData(arg1:string):Promise<main.GraphData>;

export function GetInferenceModels():Promise<Array<string>>;

export function GetLocalRulesInDir(arg1:string):Promise<Array<string>>;

export function GetPreferences():Promise<main.UserPreferences>;

export function GetScipIndexerStatus(arg1:string):Promise<Record<string, any>>;

export function GetWorkspaceConfigs(arg1:string):Promise<Array<Record<string, any>>>;

export function GetWorkspaces():Promise<Array<main.Workspace>>;

export function ImportCommunityRule(arg1:string,arg2:string):Promise<void>;

export function InitializeAstGrepConfig(arg1:string,arg2:string):Promise<void>;

export function InstallAstGrep():Promise<string>;

export function InstallScipIndexer(arg1:string):Promise<string>;

export function ListLocalModels():Promise<Array<inference.ModelInfo>>;

export function OpenBinDir():Promise<void>;

export function OpenConfigDir():Promise<void>;

export function OpenWorkspace(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function PullInferenceModel(arg1:string):Promise<void>;

export function ReadMarkdown(arg1:string):Promise<string>;

export function RegenerateIndex(arg1:string,arg2:string):Promise<void>;

export function RegisterWorkspace(arg1:string):Promise<void>;

export function RemoveLocalRule(arg1:string,arg2:string):Promise<void>;

export function RunIndexingTask(arg1:string):Promise<void>;

export function RunInference(arg1:string,arg2:string):Promise<string>;

export function SavePreferences(arg1:main.UserPreferences):Promise<void>;

export function SearchCommunityRules(arg1:string,arg2:string,arg3:string):Promise<Array<mcp.CommunityRule>>;

export function SearchForIndexes(arg1:string):Promise<Array<string>>;

export function TestInferenceConnection(arg1:string,arg2:string):Promise<string>;

export function WriteMarkdown(arg1:string,arg2:string):Promise<void>;
