// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAstGrepStatus():Promise<Record<string, any>>;

export function GetWorkspaces():Promise<Array<main.Workspace>>;

export function InstallAstGrep():Promise<string>;
