// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadModel(arg1, arg2) {
  return window['go']['main']['App']['DownloadModel'](arg1, arg2);
}

export function GetAstGrepStatus() {
  return window['go']['main']['App']['GetAstGrepStatus']();
}

export function GetDownloadProgress(arg1) {
  return window['go']['main']['App']['GetDownloadProgress'](arg1);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetScipIndexerStatus(arg1) {
  return window['go']['main']['App']['GetScipIndexerStatus'](arg1);
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function InstallAstGrep() {
  return window['go']['main']['App']['InstallAstGrep']();
}

export function InstallScipIndexer(arg1) {
  return window['go']['main']['App']['InstallScipIndexer'](arg1);
}

export function ListLocalModels() {
  return window['go']['main']['App']['ListLocalModels']();
}

export function OpenBinDir() {
  return window['go']['main']['App']['OpenBinDir']();
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function RunInference(arg1, arg2) {
  return window['go']['main']['App']['RunInference'](arg1, arg2);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}
